Add a hack to ignore logs unrelated to the tests
Some resampling tests started getting some log errors about some gRPC
task not being properly closed, which are clearly artefacts from other
tests that shouldn't appear there.

For example:

        assert config.initial_buffer_len == init_len
>       assert caplog.record_tuples == [
            (
                "frequenz.sdk.timeseries._resampling",
                logging.WARNING,
                f"initial_buffer_len ({init_len}) is bigger than "
                f"warn_buffer_len ({DEFAULT_BUFFER_LEN_WARN})",
            )
        ]
E       assert [('asyncio', 40, "Task was destroyed but it is pending!\ntask: <Task pending name='raw-component-data-8' coro=<MicrogridGrpcClient._component_data_task() done, defined at /home/luca/devel/sdk/src/frequenz/sdk/microgrid/client/_client.py:298> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f9224472ca0>()]>>"), ('asyncio', 40, "Task was destroyed but it is pending!\ntask: <Task pending name='raw-component-data-18' coro=<MicrogridGrpcClient._component_data_task() done, defined at /home/luca/devel/sdk/src/frequenz/sdk/microgrid/client/_client.py:298> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f9224472c10>()]>>"), ('frequenz.sdk.timeseries._resampling', 30, 'initial_buffer_len (257) is bigger than warn_buffer_len (128)')] == [('frequenz.sdk.timeseries._resampling', 30, 'initial_buffer_len (257) is bigger than warn_buffer_len (128)')]
E         At index 0 diff: ('asyncio', 40, "Task was destroyed but it is pending!\ntask: <Task pending name='raw-component-data-8' coro=<MicrogridGrpcClient._component_data_task() done, defined at /home/luca/devel/sdk/src/frequenz/sdk/microgrid/client/_client.py:298> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f9224472ca0>()]>>") != ('frequenz.sdk.timeseries._resampling', 30, 'initial_buffer_len (257) is bigger than warn_buffer_len (128)')
E         Left contains 2 more items, first extra item: ('asyncio', 40, "Task was destroyed but it is pending!\ntask: <Task pending name='raw-component-data-18' coro=<Microgr...k/microgrid/client/_client.py:298> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f9224472c10>()]>>")
E         Full diff:
E           [
E         +  ('asyncio',
E         +   40,
E         +   'Task was destroyed but it is pending!\n'
E         +   "task: <Task pending name='raw-component-data-8' "
E         +   'coro=<MicrogridGrpcClient._component_data_task() done, defined at '
E         +   '/home/luca/devel/sdk/src/frequenz/sdk/microgrid/client/_client.py:298> '
E         +   'wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at '
E         +   '0x7f9224472ca0>()]>>'),
E         +  ('asyncio',
E         +   40,
E         +   'Task was destroyed but it is pending!\n'
E         +   "task: <Task pending name='raw-component-data-18' "
E         +   'coro=<MicrogridGrpcClient._component_data_task() done, defined at '
E         +   '/home/luca/devel/sdk/src/frequenz/sdk/microgrid/client/_client.py:298> '
E         +   'wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at '
E         +   '0x7f9224472c10>()]>>'),
E            ('frequenz.sdk.timeseries._resampling',
E             30,
E             'initial_buffer_len (257) is bigger than warn_buffer_len (128)'),
E           ]

tests/timeseries/test_resampling.py:113: AssertionError

Signed-off-by: Leandro Lucarella <leandro.lucarella@frequenz.com>